### ISSUE TITLE
Adobe 文档的参与者指南概览 里的问题

### ISSUE THREAD

**Issue by yanlicao** [AdobeDocs/contributor.zh-Hans#1]
Issue in ./help/introduction.md

这篇文章中写道
如果您看到某段内容有问题，请单击右列的 Log an Issue 图标。

但是其实这个图标有翻译，叫做 记录问题 图标
所以不翻译是不合适的，与UI不匹配

**Comment by yanlicao** [comment]
其他语言也都有这个问题，例如 CHT

![image](https://user-images.githubusercontent.com/2255096/206727506-48a5e7ea-3dc3-498c-bd30-2d00796bfa09.png)

**Comment by lio47708-2022** [comment]
感谢您。我们会查看此问题。

**Comment by lio47708-2022** [comment]
@yanlicao 感谢您的反馈。 正在对您的反馈进行审查和跟踪，参见 G11N-11308。

**Comment by lio47708** [comment]
请注意，这个问题现在应该已经得到解决。
